export const DashboardActionTypes = {
    ENTER_EDIT_MODE: 'ENTER_EDIT_MODE',
    CANCEL_EDIT_MODE: 'CANCEL_EDIT_MODE',
    SAVE_EDIT_MODE: 'SAVE_EDIT_MODE',
    RESIZE_WIDGET: 'RESIZE_WIDGET',
    REPOSITION_WIDGET: 'REPOSITION_WIDGET',
    ADD_WIDGET: 'ADD_WIDGET',
    DELETE_WIDGET: 'DELETE_WIDGET',
    SHOW_ADD_WIDGET_MODAL: 'SHOW_ADD_MODAL',
    CANCEL_ADD_WIDGET_MODAL: 'CANCEL_ADD_MODAL',
    SHOW_EDIT_WIDGET_MODAL: 'SHOW_EDIT_MODAL',
    CANCEL_EDIT_WIDGET_MODAL: 'CANCEL_EDIT_MODAL',
    EDIT_WIDGET: 'EDIT_WIDGET',
};
